In [156]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [157]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [158]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [159]:
from sklearn.model_selection import train_test_split

#split the dataframe into 80%-training and 20%-testing
data_train,data_val =train_test_split(data,test_size =0.2 ,random_state=42)

print(data_train.shape)
print(data_val.shape)

(800, 2)
(200, 2)

## Data Preprocessing

In [160]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [161]:
import re
from bs4 import BeautifulSoup, Comment

In [162]:
# Create a copy column 
data['preprocessed_text'] = data['text']

In [163]:
import warnings
from bs4 import MarkupResemblesLocatorWarning
# This line tells Python to completely ignore this specific Beautiful Soup warning
warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

# --- 1. Remove inline JavaScript/CSS and HTML Comments ---
for i, text in enumerate(data['preprocessed_text']):
    soup = BeautifulSoup(text, "html.parser")
    
    # Remove all <script> and <style> tags
    for script_or_style in soup(["script", "style"]):
        script_or_style.decompose()

In [164]:
# Remove HTML comments
comments = soup.find_all(string=lambda t: isinstance(t, Comment))
for comment in comments:
        comment.extract()

# --- 2. Remove the remaining HTML tags and keep text only ---
data.iloc[i, data.columns.get_loc('preprocessed_text')] = soup.get_text()

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [165]:
# Remove all the special characters ---                                                                    #pattern #empty string 
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'[^\w\s]', '', str(x)))

In [166]:
# Remove Numbers
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x:re.sub(r'[^\d+]','',str(x)))

In [167]:
# Remove all single characters ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'\s+[a-zA-Z]\s+', ' ', str(x)))

In [168]:
#  Remove single characters from the start ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'^[a-zA-Z]\s+', ' ', str(x)))

In [169]:
#Remove prefixed 'b' ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'^b\s+', '', str(x)))

In [170]:
# Substitute multiple spaces with a single space ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'\s+', ' ', str(x)))

In [171]:
#Convert to Lowercase ---
data['preprocessed_text'] = data['preprocessed_text'].str.lower().str.strip()

## Now let's work on removing stopwords
Remove the stopwords.

In [172]:
import nltk
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [173]:
from nltk.stem import WordNetLemmatizer

#Initialize the Lemmatizer tool
lemmatizer = WordNetLemmatizer()

# fucntion to Lemmatization
def stop_and_lemmatize(text):
    # Split the row of text into individual words
    words = str(text).split()
    
    # Keep the word ONLY if it is not a stopword, and transform it to its base form
    cleaned_words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    
    # join the remaining filtered words back together into a single text sentence
    return " ".join(cleaned_words)

In [174]:
# Apply this function across your entire DataFrame column
data['preprocessed_text'] = data['preprocessed_text'].apply(stop_and_lemmatize)

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [175]:
from collections import Counter
import pandas as pd

In [192]:
# --- 1. Filter and count words for HAM (Normal Messages) ---

# Grab all text where the label is 0 (ham) and join it into one giant string
ham_text = " ".join(data[data['label'] == 0]['preprocessed_text'].astype(str))

# Split that giant string into individual words
ham_words = ham_text.split()

# Count the frequencies of each word
ham_word_counts = Counter(ham_words)
print(ham_word_counts)

Counter({'6': 12, '2010': 4, '1': 4, '1230': 2, '2026472972': 2, '1030': 2, '10': 2, '11': 2, '5': 2, '4': 2, '30': 2, '3': 2, '2026479071': 2, '13': 2, '34': 2, '66': 2, '100': 2, '1545': 1, '282009514': 1, '16': 1, '72010': 1, '61720101212666666666': 1, '1772009646': 1, '172120097266': 1, '02200911382': 1, '109': 1, '2026475548': 1, '12010114724120102130200870010112302050700000304085213060116012002009754050751921': 1, '142024191420': 1, '032009334': 1, '171620091001': 1, '20': 1, '622009850175': 1, '5132290': 1, '20264786332026475548': 1, '62010114620100606': 1, '182012338': 1, '17120091155': 1, '1996': 1, '172009539': 1, '2120091131221': 1, '7': 1, '20150484105739629051320150045554201504841057396290513201520211201215': 1, '171220121126371212': 1, '20100808': 1, '22200926': 1, '123220120264755482027364535': 1, '121320251421210420101141146114': 1, '52010541': 1, '272009650': 1, '282010503': 1, '17312010854': 1, '6745': 1, '072009408': 1, '27200965813': 1, '0220094046': 1, '202009812': 1, '18': 1, '1792010742': 1, '1414312006200952141402092030': 1, '22009623320091925200219411019412002405030020012100019402001193919412005': 1, '23201010247251215': 1, '2120091049221133351': 1, '245': 1, '53': 1, '2220091247': 1, '2': 1, '800900900900100010001030123010010011011520092303003304002181516530545545630630655700830883584523': 1, '5799774534119800144023664833110000025118312010224831201022481932193019324200919301241651026002011200957200920101541071820102010': 1, '1245': 1, '28867348258114621431842826552862826': 1, '22242009100526': 1, '2026477209': 1, '2525': 1, '200': 1, '201023232010200820092010201021': 1, '8': 1, '1302': 1, '9459551000103010301045105010551100200200230245315330340040043043044544550551051551563063565091593010002014204390576307706302015': 1, '17132009641': 1, '56': 1, '262010952172303': 1, '31201012170125106': 1, '222010300000200915500000': 1, '420091030': 1, '10401972': 1, '10301025': 1, '52010711': 1, '60': 1, '910': 1, '10132035': 1, '12009409': 1, '112010': 1, '172320104095090': 1, '945126471512': 1, '14': 1, '12010337': 1, '2220097280022200919545060802050202025020501001720052020331515': 1, '9': 1, '09200970198319871193919601964198319992008': 1, '162009707141': 1, '42010800': 1, '320091008040209060900': 1, '192010': 1, '682583583584084591591544595510101020103010301045104511581150125081250100100115130120020021521523023525030035035021710140021740050021720150484105739753051320150045413201504841057397530513201550552052560060061073060201504841057397530513201550045414': 1, '21201099060000197310135': 1, '072009714': 1, '1320091204': 1, '92010942920101918500001504': 1, '0122201049434840201264272012201239343538352012454446444536454820125136543341253826304348484352192518171562815242422035825201203582520112012201219142522102016201717181718262213151811151513161618201514261314222322321366566676231142212211311211112311111111171519191314201422012201227302532133216646265598358769810104109320122012486894444524191604085637443647131432853523316433164326364431834355455505010010062444554484486631730434235424692272443345254244333243254532154465623313942336758484445543224534444201244386354048378760459184651395333222132122114222327351259777183435545550501001005940415044388156153448483749541132751222221221322311367786459542511926344642696453213222122284769520124648540424938906444889474940525262214312121321212645748647183435545550501001006041435144428459163448463848521029762222121322221222467752485114352212736464072665222222211137555762012456853742493884663678534393242322221432311321432312141282113151510918343554555050100100584242514441836015303738304043820651322221331233131331015151313127151543512328373732565242223333233315131515167486864344514091664891125253445693121221223211323318343554555050100100614542554741836217355154424956143281121211131223232132455323283950437568582112123123180921251912212010201020102010200920082007484749475067444845454738191425449114023212318367483340324183151177854495347745610712108129161233232323180921241820102010201020102008363135333751504951301015141431332229416915454735461728257422127232330363323413326403052352122121111831201020074115251333702210386416434432431434269442227252534293526403327413151372112211111825123115133201020102008200720072007200738283428201817262520252220163545434555606522322221130609263625346244318624544434353342520282619302139402212222221821201020073022434725302212132541418914411103189111091416767277767081768272111111113712281057312529355489878589888590888879111111111141018510128115782147987219817981837883827383111111115122241316913519124191314101119137573767469817575671111112020124348135394634866549921351534557429946148999518343554555050100100583838494037765414345354425156153480898997911541471923325144756960997892012182125201020102010434040494848912113140859334237465294587548454540735713514151015112013321433222183435545550501001002945413345491030645542424549457953211510131934914121242322324039605750415528313516410101233222252009180921212418820102010201020102010201020094035333333402545434247424553131921152113183344434323857628314433695250861456594155203910781171210108321433311183435545550501001004835354341307148134053534152642137761099134551210223241331374120253149536965541249813322221809212124122420102010201020102010200820103834343233553350474952483548101514121761733332423334657354128391024381163373838355745262228262032253230111212111170921212420102010201020102010343033322838313131232637353449121213813252141411142128371948482848293874442354511834355455505010010081514131213242688838182868595917142551235314112317158188717881526541809212124201020102010201020101312121513838081798049766275065181908203582820020358282008004621944800462194419992010': 1, '1722200910046': 1, '8201081382010747': 1, '82010648': 1, '24200963515': 1, '11414110022024': 1, '212010201020': 1, '171620091037': 1, '2023432905198611994501515304089156': 1, '171720125486': 1, '8158258258308308458459159301000101510301030113011301140120012101215124512451201201402002174325335425': 1, '132010233': 1, '2120120404': 1, '88': 1, '24': 1, '17142009535': 1, '1922': 1, '51220173459642122012052064212026479598': 1, '171220096426': 1, '10301230': 1, '1220101107651': 1, '2820101229': 1, '130': 1, '120101227': 1, '2005200520052026471709': 1, '715329': 1, '17420107096': 1, '650': 1, '2201023800': 1, '112009656': 1, '252026471709': 1, '2120101132': 1, '175172012914': 1, '142': 1, '082009913': 1, '0323201024201003252010032620100327201003282010032920100330201003312010': 1, '220168052052020264772832026477288': 1, '2920091058112909292009': 1, '1620091108615096': 1, '2122026472972': 1, '29200911206628200915050970902009092926709414816309092914550025242009092918566807524282009150509709070201026000025423014120213861766116206176611626': 1, '1218': 1, '062009415': 1, '102091030': 1, '2123': 1, '272012': 1, '312010103511': 1, '092009729': 1, '1420120806': 1, '17201095511396922001515201040320011341120011999672113969212010070909213020533107310251262010': 1, '815825825830830845845915930100010001030103010351035105071100113011301200120012301230100100130130230230315330415': 1, '8830': 1, '332221415105002054506153061517454174518155183061900710050014145301103190017002214360630778561930777715903930799715903': 1, '132009113266': 1, '082009355': 1, '600102026475548': 1, '2920091018': 1, '63201012011513351117110410001015520001997155001417261515': 1, '132009406': 1, '393962257442248121631714432132029781110162417468172293': 1, '040220252201011414114146': 1, '20150484105739700051320150045701': 1, '17302010858': 1, '220102312211': 1, '2320096126': 1, '272009': 1, '20100111608481811201063046505013104241365452572975415526122003561591119204414823119': 1, '4200940822': 1, '52026479572': 1, '000': 1, '745': 1, '1712010850': 1, '2014204390576161906302015': 1, '2720091018': 1, '361': 1, '230': 1, '3020099391313': 1, '52009101820091111041165515735137941172200120044810175411120012501200730052471960501275175': 1, '17122010953': 1, '1114142512172025': 1, '825825830830845845915915930793010001015102520010451115111511201120113511401200120012151215100500105120200325335420': 1, '12': 1, '212010742': 1})

In [193]:
# --- 2. Filter and count words for SPAM (Fraudulent Messages) ---

# Grab all text where the label is 1 (spam) and join it into one giant string
spam_text = " ".join(data[data['label'] == 1]['preprocessed_text'].astype(str))

# Split that giant string into individual words
spam_words = spam_text.split()

# Count the frequencies of each word
spam_word_counts = Counter(spam_words)
print(spam_word_counts)

Counter({'10': 3, '30500000120': 3, '00': 3, '44704570518420447045705184': 2, '25705100': 2, '215215215201070': 2, '22222222222222222222222222': 2, '10123458': 2, '4952001': 2, '75100301060521511614314904911226': 2, '509': 2, '1944142005199219982000200420200414200530042540100': 2, '23310': 2, '36759000001001194414200519921998200020042020041420053004': 2, '23': 2, '1500000000199730601060': 1, '222222222829222829222221823222222240225222214222351976402280022164967682922': 1, '18611342511342835850500000028352523492726567': 1, '125265310100127300000010337503300001032606746649111074038447746': 1, '32003072033311867477163300339920030720406010003387057969744296569033462': 1, '50000000': 1, '2500000000712360400023324297270200233242972702196019603214124401857806142115928311139685': 1, '15200715212003592301060226765493429203': 1, '202022422220222029270000000022220202202220222006220': 1, '52783237849910930567302109989648425288': 1, '222222222224222222222119962242006222228292222223222052212222222222222222222222222222222222222222222222222222222222222222222222222222222222222222322222222222222222222222222222222222222222422222222222222222222222222222222222222252222222222222222222222222222222222262222222222222222222222222222222722222222222222222822222222222222222222222292222222222210222222222222222222222222222222222222222222222222222235114022': 1, '25027804682861220202027804682861225570995': 1, '21050000026126116396630637752865114374056758337': 1, '3196078603010101365810461111149982499763': 1, '2000': 1, '15000000301237626344114866530593785': 1, '120000400000260000150000120000267170246220000015002512000500002002600900111433971200005580114339752607011433971424124956218594695420005719953517103057010142525118883468': 1, '12767990311019992010': 1, '52120021551550000031550000040602348033791090': 1, '301060200020047101': 1, '322225078195572222222222222200222281725002000292222223281292282292222832922152222814292231744022': 1, '224222222927000000002222222232006220062861917234608755105105': 1, '275275128316527135572810022212308778867316892515000000275100': 1, '14110075782000283000000070255': 1, '920035481214904572920032000000000': 1, '206126131200035': 1, '24223553070': 1, '327839835788387376253436538737625343662222222222222828250020002002922222282825292222822922252825270521002222222322222': 1, '2323417592758340232222220252829200122222223010222222340222232': 1, '000000': 1, '3222240235222222222252000200020028292222282922222302102829210222222222402332224023100222200322232222322224023322240233522222222225200020002002829222228292222230210282921022222222240233222402310022220032223222232222402332224023352222222222520002000200282922222829222223021028292102222222224021002222003222322223222240233222402335222222222252000200020028292222282922222302102829210222222222402332224023100222200322232222': 1, '00473270': 1, '184100401050': 1, '82613120000220000201201234': 1, '3222328292222282922228292228292222800200020002002292222202228292222222222222222': 1, '5202060202020202020': 1, '2': 1, '22020929220922020012220222022022220102261312000220222200002012222202202202202203022202220222022202022202022022022020220': 1, '779797791955103': 1, '33306040608435183942': 1, '202020202020': 1, '3029211001099129129915253235104940252425933212833422429015122512253295309022312358032398902140291594342242292504310112420291453352933150325253015802039002590153201531350940559152155329020029052500020281395202909303509425000950291253152953123229015350943592530229532912014529535522245922503520': 1, '22222222812292281721292222199397296962222222282922302222222222232812932822932832928429328529322222242322122335316335764234022544022': 1, '202020': 1, '22312000': 1, '765326121080': 1, '2000200119122005612200567000001912350000': 1, '75100301060': 1, '222222228152229222212000222222222321522002000300250402102222228540229222': 1, '0310001002031000100203100010020310001002': 1, '222222922829282922222832500200020029222202222225402222': 1, '128713600000000136000000001995199819981363600000035605': 1, '20300120750000000750000000122020999': 1, '202020202020206200020203620175000000020202020032020202020202020202028099202020201750000000202020032020202020202050000000020202020202020202020202020202020202020202020202020': 1, '03620511528389153120891325010991291290253220222316114194034352513434323210045042920822915212091350325112919025092990252532420041595052213191052829222955292351532530902232521935320333235290214929211594229345331012009355522415205330055253192285002902535080905501054520199290902530158992525082402829082062505591505525591335020282020002532062505524291180095029125320993012322905250592029825309122182913202295329150349923353294231611': 1, '12087281407710606': 1, '9935102102225151001030031655': 1, '12582720011050000000105000000056040': 1, '415000000020701010033': 1, '4210123104': 1, '1600023182302345133233333433533': 1, '500000300300000480000182020051202502006460000': 1, '232222228292223222152528222922222282922222840229222825296510652522222222222': 1, '222222226220002222282922625002000200228229222222222222222625002000200222528292222222228020222222222': 1, '85332320342358996710566913313390303100039506073130131139205345265329439091': 1, '55000000020074': 1, '5050': 1, '2235940222322222302200428583292233222222222004112302539608122218252222222322221260224022359402222222': 1, '2020202020232003202020202020202020201200000020202020202020202020202020202010020202020': 1, '222222221524822222222292421200022103222222222222222222222': 1, '25000000003010101002003': 1, '68540': 1, '22200285000000085000000020': 1, '15200415153152012': 1, '33225072360683285114022335114022329222220042220049228922922222223281292282292222832922252222250723606822283292222222285114022335114022329': 1, '205': 1, '226': 1, '002267652474320031226151526200392301060002267652474392': 1, '3333222022204232202024233220222023322032320322320322220000005485657': 1, '4005840': 1, '200268': 1, '32222222222222120012222322222212222212260402222235123402335123402322231222322222222215065447': 1, '105000001982199235605': 1, '23322222223222222282932222222228132529222222222220132521002222222': 1, '335014022182200228222521202220022822258424222002282229222225222221998222275200020002002829222222222223020002000200282922222222222222312222222222': 1, '20202020202020': 1, '22222227222222': 1, '11233246676944311220208419541171465562826': 1, '5210123104': 1, '17118245000004': 1, '180000000020202020202020212000202020202809920202020202020202202020202050352010520202020202020202012022020202020': 1, '2773211286612121002040355': 1, '2920021241003056503': 1, '2020619992500000000202020202500000000205203632323223632232232223213232363223223222323232220653052020': 1, '2000106': 1, '322340236614919460232222222222162222262829222222222222222222': 1, '186113425113428358505000000283525': 1, '3553110030601027834247661': 1, '33310000310000233008055002003310000333033805531000037733805573030': 1, '234803320681323417599055218123411728033100': 1, '18594792020152020062020153120002020204050101400226788575971030743690036477417204951863393': 1, '22282293328293282923152000200020028292222282222292233222222003211213251215232222222220282927552327115076103228229222222829': 1, '2222228292222920042228252500200029222222222': 1, '2119892920048000000122031578274647575': 1, '727252003200312262051414': 1, '25990199915025032576040999321461417895840294944': 1, '305000002040750542004': 1, '333333923233335200000333333333333203332313323': 1, '8790198019901990904525705123': 1, '8621200320030720604030000': 1, '3234175991593340222222222221983222221232020002002822923122022702829321027102341759915922222222222': 1, '1631000000000': 1, '302700000020': 1, '222222222282928292228302000200020029222222222232231423233323228292829228292228292222222': 1, '202020201500000020202052075202020200920': 1, '21200130306040': 1, '25667223422003232222222200022222528222922222222222229229292292222929229222222222222222222': 1, '523070': 1, '1237942012533554012132511515251254051254054200540200251252002510002540310001251251000125500012540250006251255000625250006254012500031251252500031251355937531253551301003010000210100002101': 1, '15100': 1, '454477837082973214967922140107250496792214010725001552369249117839829855890': 1, '1715001842555031626662624': 1, '0014': 1, '360000000030601014': 1, '12': 1, '4500000000198019901990450000000020755': 1, '220051751755040105000000001968': 1, '167202020120220320420520620000999753520032020022020': 1, '50000000000700200330000000000480000000020031234567': 1, '12105': 1, '1061950272': 1, '010088842005175019983070': 1, '400000000012345630100020047101': 1, '155301063317902491067504386719': 1, '22231543135339666313133966330220779895654114323454577820': 1, '122007250000088860885000000050000000010': 1, '4934043200162001701055000000101055000000454510': 1, '2222829226219992222282921225002000200282292222222222222122500200020022252829222222222226040222222223402222': 1, '22222221922002223923002000300228292328292282922829222222222': 1, '2348058437715': 1, '02312033380873301619350560113812151733811': 1, '942004214115118131111111111111111910020360131445627581192456809361014022354562758119255692952098953606070167943864496092600348785612144873790616972296902807149687275243561508819127529283256176109665072321094045627306434327635808670515335436232446198615625455886115316170300549906925840512814435366628308456138642026331034329024592992117380061153744059940999944965305296607544183611218771912302070910245557335889825686117099330896722301926647959290939672512276455388929307673415437132597727175532603678884664149095266147599646784625713659807819582710247175005579547310390772068816124351538199559505180170456004962086560904606645246764353555434974883988410468154109114402167449120718430242356647542629031224151586236323327434545222586363718349367793615577795971268807547997133041855253527679235434163346702410233596833696428165893459029690886317446050789639521069161952125185471462571483013415225972404083793590499073956188526383695598091096509566274362021374711785365721698785027225950178633838657341965492926266424017132290621956457197229510209855252735469622331634390166749434567241060741930186491204993431596735718735909611810501056478002518985635925063158019367583467815451002705170763497497571595735780772681462777343575082552715537818807127104321071461837761098792558616523684260862148570536311577072742639862344859701146259421620473619908770945990523990991359530365338027981999702562514442905086718417421756421276932856559535103924723515430551189341987130989348831334722176030241076207569730522544441542515257038695827206883583299711824387211134628141881338485050317795139826768496056104604731999784461702175884009558291312908773811564096613145165517616671151219115132508347342756109913293636186356047988153558301288213456127523263057462644427453738114090525191096552004538250264070764717630884215507810618621165025730555966613760057780778570095484301469168398970110567698347532067289020579050555167559322056158890310188454714965063773545199706098629696553426994611948091355095530473500278108902626106137859926981581069126547752580677449816372969376666584016198254202404570452219400947086567160395763009693676040028445463435397317016128905666173549575576252700587421503751101461583045142843976168549536546504352212425471826189851062422455610373208392039311438217191459095219599077763048675571587334945871199683556346313925114034061606639345447247038196445981958690507495274591082540046440352422515765143055440118519326056776981873984549055123723971625674678803663041729716144680695503944586109470658937654560568563576864860895421365861955586738735725989042511848658005913023955533432896728543818568667940004454614924100693720412048965066514681433827344398975729313809323732354272772395719265847121585536478735218507560353289258732944007189074951206712794125619713898661311129228732865273537166949217500683454411246871480826251812496283065456446919168806078645645607342401491520816095592616893936240153605540400576876159913677607273549164713824563426403754707154467100287099300323654706106021298337750817686037897808535772205862018945525733042888368505447985296866057090257753352550296508360045621939009005962171980335912195758256405916977517427800019579649583861129404017958612598260805807061551999708873629678309345022234018706154614753035462055121268377120714920524355830154054797236495361309651875761906436950681736912758942001804559168709849679311447043501367326824216512755234356095357813992100435738891425621378161020827127420165267148642407487053813998952286381053794270469323859292749439695827183922317409043482388572022153199883311160529847534225451298358892035379564591187896922782240243504675869904859188696560701019305101417742020371490307531336014759481273742057675096259567769613551892471249285164123512020141604385002470067711448990114350529131758176152288561588715176051193711107676754355970783794314867832526105168211387371110170463601996040474703243140504476401698476498066320063956522955873332330257829184976065386137215533417335476183311376440674209109856747684873177156549256193187655420620992223286423444215604300069350167461537836577006170071308546608140231408521570064827775305035466150314100709494740286606360265244818861753892884708466425294665276883617691978773608821988673874260782755838928553036103942556773004751250172365709353781613943605448000285850519628906414321473761670752204208642738311113109431441755582217267075198194998493619490714890407125609331396070499281204750991703086436046823252264740685343771947520172615117425470174317374600747595321609111528861349981612445552861216007155798518338655672937716748110769661533136193145395356046545358824443043602460095016025629459948379701047125287204716150431636117932550235819917786656374913821713067819623045442552970430535190850777296299932207450675490005359521308624963571386402541272857803413514761336358104898055232823693815237771531332251105341122460144579809060775507446489855017441071740154210808154135727941229937197102245722101582556320914636041632539506360955228356383396765080951967206668027303990337727512007569184707922731620855497612152411190375506562510332365139520567289718063431593864719048521015136089293132137245213490453947030643440474889035116806825964854341300619647061025428014296332134425261977015339367585452881471105026027453539455191871472338852864288593119851658529445273008406379414393844327391361288411065318109635076373074314334392681110197991405584460641510014866187152657053139378222877098154260494569689525226118772620005233121395766074375479829871106921161252900711711922193610324019610274387121156084276164037282241330892437135394423872379142409546124643003141541400698603194710135117845542085603080470035206587218063054409324110929870252955336635784015857550223965396245929614118042859879052387869045077356330039364284191427439364974516189420253941151961333659647432131049995813241536744255173709758496151369408741896125841795442122363824752411649881879918957464270228491066144278445252856515553745723305367455826159473828197254612692253564191584203612252050215610151510207708420378374773131215152331043914619941529811266392548771461122082492882500021533767092120960931323926158370088996070950949605345010263409001592533107142709051934771202727815532827432960463146922895350760125426184793278125524244762560278491426361115731405393671881127714035811748196023123377755045802963495869975448597434673470122485336616443611101545742809969689936014442831806184896049086371050142801284105731778758702399841522751213525571981708343309043704429378905213930233205109798484542515885775151762016528410722732027469556724157713058303894042661000573691571810492348546056124506606941535561405701390094540530003063452281254513717672923987570061592434688817942602371793292385123573262886014308424050613154597826039381254268784371776576585561050549572811596322037148113883989592248596172349798507363053463574094718105850047801903619045506088001352978391496604069087003223474552820115363942795974055591957762111989135775915571862465079147537002474611977396891653731725763158959087870125704946505138294636322514614603704435028232051603964447025055970687512582339441548863476034340552127622393875420039097068727022763952907953530994105106099613545909767265817229489293271011219245561991398454356581072922581558526000906734126102660470301256015644681019127140676449658888553169731468136476062868569825458288508807039252354572209290620140109334985485786647529637478942035075151149264592497776517813160490253151145337408412837164712752519798192898310753122381271131425129217981278048778712608587110134158185030492150104407940403044140557790048753818718525098029586963223955362949748591408982331845535777982725376391473214075036000245268767158892810855712689876599715415998849535256766027604410476364451033778954855305915255451496604523145682752106423390129727122529581125590087658596892911273686946018060217608570604700553555810946819897472725311175580974607533686227126438587746573897848344555491775713534890780392044830963306320093592099920569365400827815045717725767757331628031817491030511697280253509074033858271366663390722947138432066542165058244495837768129483402607404920305454470648803151495904892812612864348701042344823581508192917537885569530533533692435828166118427591041985832513522864120958824306078769511275013570850944582304451497171925748166983209174516107299361119910078040525820475239763952907576206300704345408550136698826606259608815060261777379310942599812387343412539174791690917275537339745355244281312147257945524250700028698571745667862236869804502053436449113439075920062743403374733852808522207347049121357113566532459529825610032823395630440626910533646078360799640874606054813842432532213652127425596375299026646361755965151648658335754703069420460168751371473032788240235515559918762239344812069302043086031432888816287682258714671126567742939582225773591423605713012564897284660553799378046911960953992471470492441544154712057058522378693616176162653641572251280253833411700600862391567176251462549386694237731145176335122520210452726008639949824573739421221385047167696301062038142031124633818991319521007144680423252572098872065956126446049045746704604703355600504861540649460054155180548988067849715939924389031132222917618069923040573875781232050166465392908390164207022279060041974903064617737123674237155477355404416491911518163077141220396011260995217355013954069199660216444998074073139205420213981770595762850286139081300106062190446016208483939139263119606450737544330375072181059037727918504781633130116877555135654245322100522862142844995731289362868574073580776102617204055498238456450278076112816304780311232468831750396055621892848344592914609130776194981524306530562434255321176111774944378827387846272417339531603551883581408673091758658157155': 1, '6': 1, '200320032050000020': 1, '1857025522': 1, '23200591120042520055050': 1, '3222322222242550200022200422242550200022829222307022222222224022': 1, '95804205001437252004139916745050': 1, '32228199822222322222222282922222292222302000200020020092228292220222222223122232222222233222222222259090002909972232222222222587700028771132': 1, '2030250205020': 1, '3950000000120032000200339500000009500000003035605': 1, '2222222222222312000849221240022222222222222222222222228296252222222222220222': 1, '2520004590199810600000000600000000652010510079': 1, '22222222625282229222929222222222222292292292222292292222222222222285402292284022922222': 1, '428706040': 1, '1222300673222741222222222228293023322222222000205052222228294223521725222222': 1, '130000000025005874100020002000020150401037745140661340803736767551179628165692': 1, '230286025457358671314649247257733882533131199999015025031070000000201235': 1, '1831070255': 1, '35555555555555555555555555555555555555552222222829222212250020002002829222222829222222830292287029222222222402222222402': 1, '870763593730': 1, '15200317123': 1, '200020105202014142020205009092030015': 1, '826120000201': 1, '2285252001203070': 1, '222222222292292222852829222229229292232': 1, '22222222222222222830292222222228302928292222223122232222703022222222822922222314022222228229': 1, '62000

In [178]:
print(data_train.columns)

Index(['text', 'label'], dtype='str')

## Extra features

In [179]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,0,0,106
535,I have not been able to reach oscar this am. W...,0,0,0,101
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,0,0,141
557,I can have it announced here on Monday - can't...,0,0,0,52
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,0,1,1750

## How would work the Bag of Words with Count Vectorizer concept?

In [194]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the vectorizer

# lowercase=True and stop_words='english' to clean up text automatically!
vectorizer = CountVectorizer(lowercase=True, stop_words='english')

#Teaching the vectorizer  vocabulary and transform the text column into numbers
X_train_bow = vectorizer.fit_transform(data_train['text'])

# Transform the validation data
X_val_bow = vectorizer.transform(data_val['text'])

# print matrix 
bow_df = pd.DataFrame(X_train_bow.toarray(), columns=vectorizer.get_feature_names_out())
bow_df.head()

,00,000,000000,00000e25,00000e251,00000eur,000066,0000ff,000m,000million,...,â½s,â½t,â½ta,â½te,â½tica,â½to,â½trangers,â½x60ã,â½x70,â½ã
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [181]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

# Load the vectorizer 
stop_words_list = list(stopwords.words('english'))
tfidf_vectorizer = TfidfVectorizer(lowercase=True, stop_words=stop_words_list)

In [182]:
#Vectorize the dataset (Fit and transform train text, only transform validation text)
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train['text'])
X_val_tfidf = tfidf_vectorizer.transform(data_val['text'])

In [183]:
# Print the shape of the vectorized dataset
print("Shape of Training Vectorized Dataset:", X_train_tfidf.shape)
print("Shape of Validation Vectorized Dataset:", X_val_tfidf.shape)

Shape of Training Vectorized Dataset: (800, 23238)
Shape of Validation Vectorized Dataset: (200, 23238)

## And the Train a Classifier?

In [184]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [185]:
# target labels 
y_train = data_train['label']
y_val = data_val['label']

In [186]:
#Initialize the classifier (Using Naive Bayes)
classifier = MultinomialNB()

In [187]:
# Train the model using your training vectors and training labels
classifier.fit(X_train_tfidf, y_train)

MultinomialNB()

In [188]:
#Predict classifications on the validation dataset
y_pred = classifier.predict(X_val_tfidf)

In [189]:
# EVALUATE PERFORMANCE
print(f"Validation Accuracy: {accuracy_score(y_val, y_pred) * 100:.2f}%\n")
print("Detailed Classification Report:")
print(classification_report(y_val, y_pred))

Validation Accuracy: 95.00%

Detailed Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       125
           1       0.88      1.00      0.94        75

    accuracy                           0.95       200
   macro avg       0.94      0.96      0.95       200
weighted avg       0.96      0.95      0.95       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [190]:
# Your code